name: Daily Telegram Bot â€“ Goudenregen

on:
  schedule:
    - cron: '05 14 * * *'
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/telegram_template.yml
    with:
      CHAT_NAME: "Goudenregen"
    secrets:
      CHAT_ID: ${{ secrets.CHAT_ID_GOUDENREGEN }}
      TEST_CHAT_ID: ${{ secrets.TEST_CHAT_ID_GOUDENREGEN }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
