name: Test next 30 days â€“ Antonius

on:
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/test_next_30_days_template.yml
    with:
      CHAT_NAME: "Antonius"
    secrets:
      CHAT_ID: ${{ secrets.TEST_CHAT_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
